bot_2_joint_publisher:
  type: "joint_state_controller/JointStateController"
  publish_rate: 10

bot_2_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: ['bot_2/bot_2/left_wheel_joint']
  right_wheel: ['bot_2/bot_2/right_wheel_joint']
  publish_rate: 20
  pose_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.03]
  cmd_vel_timeout: 1000.0
  base_frame_id: bot_2/base_link
  enable_odom_tf: true
  estimate_velocity_from_position: false

  wheel_separation_multiplier: 1.0
  wheel_separation: 0.3208
  wheel_radius: 0.0425
  wheel_radius_multiplier    : 1.016

  linear:
    x:
      has_velocity_limits    : true
      max_velocity           : 1.0
      has_acceleration_limits: true
      max_acceleration       : 1.0
  angular:
    z:
      has_velocity_limits    : true
      max_velocity           : 1.0
      has_acceleration_limits: true
      max_acceleration       : 1.5
